---
# task steps container images
images:
  bash: docker.io/library/bash:latest
  skopeo: quay.io/skopeo/stable:latest
  buildah: registry.access.redhat.com/ubi8/buildah:latest
  s2i: quay.io/openshift-pipeline/s2i:nightly

# source-to-image builder images, each language represents a distinct ecosystem the builder supports,
# sometimes it includes a specific version
s2iBuilders:
  python: registry.access.redhat.com/ubi8/python-39:latest
  ruby: registry.access.redhat.com/ubi9/ruby-31:1-50
  perl: registry.access.redhat.com/ubi9/perl-532:1-91
  go: registry.access.redhat.com/ubi8/go-toolset:1.19.10-3
  nodejs: registry.access.redhat.com/ubi8/nodejs-18:latest
  php: registry.access.redhat.com/ubi9/php-81:1-29
  dotnet: registry.access.redhat.com/ubi8/dotnet-60:6.0-37.20230802191230

annotations:
  tekton.dev/pipelines.minVersion: "0.38.0"
  tekton.dev/categories: containers
  tekton.dev/tags: containers
